language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-29.0.3
    - platform-tools
    - android-29

before_script:
  - chmod +x gradlew
script:
  ./gradlew :android:lint :android:test